name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run JAR and check for startup message
        run: |
          JAR_FILE=$(ls target/*.jar | head -n 1)
          (java -jar "$JAR_FILE" &)
          PID=$!
          SECONDS=0
          while [ $SECONDS -lt 20 ]; do
            if grep -q "Started" <(tail -n 20 nohup.out 2>/dev/null); then
              kill $PID
              exit 0
            fi
            sleep 1
          done
          kill $PID
          exit 1
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: dungeon-crawler-jar
          path: target/*.jar
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}