name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run JAR and check for startup message
        run: |
          JAR_FILE=$(ls target/*.jar | head -n 1)
          nohup java -jar "$JAR_FILE" > nohup.out 2>&1 &
          PID=$!
          SECONDS=0
          while [ $SECONDS -lt 20 ]; do
            if grep -q "Started" nohup.out; then
              kill $PID
              exit 0
            fi
            sleep 1
          done
          kill $PID
          exit 1
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: dungeon-crawler-jar
          path: target/*.jar
      - name: Create Release Tag
        run: |
          VERSION="v$(date +'%Y%m%d%H%M%S')"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $VERSION
          git push origin $VERSION
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.create_tag.outputs.tag }}
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}